"""empty message

Revision ID: bae0e5199f84
Revises: 
Create Date: 2025-06-24 18:49:43.257224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae0e5199f84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_back_users')
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('razorpay_payment_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('razorpay_payment_timestamp')
        batch_op.drop_column('razorpay_payment_method')
        batch_op.drop_column('razorpay_payment_amount')
        batch_op.drop_column('razorpay_payment_status')
        batch_op.drop_column('razorpay_payment_id')
        batch_op.drop_column('razorpay_order_id')

    op.create_table('call_back_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=120), nullable=True),
    sa.Column('lname', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('mobile', sa.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    # ### end Alembic commands ###
