"""change cibil_score to string

Revision ID: 0ef545a2936f
Revises: 86c2238554a7
Create Date: 2025-07-01 18:27:26.073028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef545a2936f'
down_revision = '86c2238554a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cibil_score', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_provider', schema=None) as batch_op:
        batch_op.drop_column('cibil_score')

    # ### end Alembic commands ###
