"""Add candidate_name and program to LoanApplication

Revision ID: 5bf1d92da01f
Revises: 
Create Date: 2025-06-25 22:35:39.992000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf1d92da01f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('program', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_column('program')
        batch_op.drop_column('candidate_name')

    # ### end Alembic commands ###
