"""Drop registered_user_name from LoanApplication

Revision ID: 665fbef68556
Revises: 5bf1d92da01f
Create Date: 2025-06-25 22:41:21.754163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665fbef68556'
down_revision = '5bf1d92da01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.drop_column('registered_user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_user_name', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
