"""change LoanProvider tenure to JSON

Revision ID: 86c2238554a7
Revises: cea22dd40359
Create Date: 2025-07-01 17:33:12.468060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '86c2238554a7'
down_revision = 'cea22dd40359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenures', sqlite.JSON(), nullable=False))
        batch_op.drop_column('min_tenure')
        batch_op.drop_column('max_tenure')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_tenure', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('min_tenure', sa.INTEGER(), nullable=False))
        batch_op.drop_column('tenures')

    # ### end Alembic commands ###
