"""empty message

Revision ID: 9f1ddd1ac448
Revises: 
Create Date: 2025-06-30 09:52:50.374981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1ddd1ac448'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mobile_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('token', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint("mobile_number", ['mobile_number'])
        batch_op.create_unique_constraint("token", ['token'])

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_total_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_amount_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('approved_loan_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cheque_cash_payment_mode', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_comment', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cheque_cash_payemnt_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('cheque_cash_payemnt_amount')
        batch_op.drop_column('payment_comment')
        batch_op.drop_column('payment_timestamp')
        batch_op.drop_column('cheque_cash_payment_mode')
        batch_op.drop_column('approved_loan_amount')
        batch_op.drop_column('total_amount_paid')
        batch_op.drop_column('program_total_fee')

    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token')
        batch_op.drop_column('is_active')
        batch_op.drop_column('mobile_number')

    # ### end Alembic commands ###
