"""Add token field to AdminUser

Revision ID: cea22dd40359
Revises: 469d477892ae
Create Date: 2025-06-26 16:37:53.343482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea22dd40359'
down_revision = '469d477892ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_admin_user_token', ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_admin_user_token', type_='unique')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
